name: Cypress Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      HTTP_USER: ${{ secrets.HTTP_USER }}
      HTTP_PASSWORD: ${{ secrets.HTTP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/results